apiVersion: v1
kind: Namespace
metadata:
  name: autoscale
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: autoscale
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: [API_SERVER_IMAGE]
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
