apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-pass
  namespace: database
type: Opaque
data:
  password: [BASE64_ENCODED_PASSWORD]
